[package]
name = "toolos-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
interprocess.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toolos-domain = { path = "../toolos-domain" }
tracing.workspace = true

[lints]
workspace = true
